config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations:'users/registrations', sessions: 'users/sessions' }
  
  authenticate :user do
    resources :users do
      resources :copies
      resources :friendships
    end
    resources :copies do
      resources :loans
    end
    resources :authors
    resources :works
    resources :publishers
    resources :editions
    resources :friendrequests
    resources :loans
  end
  
  root "demo#welcome"
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :work
  belongs_to :publisher
  has_many :authors, through: :work
  
  validates :work, presence: true


end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @editions = Edition.all
  end

  def new
    @edition = Edition.new
  end

  def create
    @author = Author.new(author_params)
    if Author.where(name: @author.name).empty? == false
      @author = Author.where(name: @author.name)
    else
      @author.save
      @author = Author.where(name: @author.name)
    end

    @work = Work.new(work_params.merge(author_id: @author[0].id))
    if Work.where(title: @work.title).empty? == false
      @work = Work.where(title: @work.title)
    else
      @work.save
    end

    @publisher = Publisher.new(publisher_params)
    if Publisher.where(name: @publisher.name).empty? == false
      @publisher = Publisher.where(name: @publisher.name)
    else
      @publisher.save
    end

    @edition = Edition.new(edition_params.merge(
        work_id: @work.id,
        publisher_id: @publisher.id
      ))

    if @edition.save
      redirect_to edition_path(@edition)
    else
      render :new
    end

  end

  def show
    @edition = Edition.find(params[:id])
  end

  def destroy
    @edition = Edition.find(params[:id])

    @edition.destroy
    redirect_to editions_path
  end

  private

  def edition_params
    params.require(:edition).permit(:author_id, :work_id, :publisher_id, :publication_year, :isbn10, :isbn13)
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def work_params
    params.require(:work).permit(:title)
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/views/editions/_isbns.html.erb
<div class="form-inline">  
  <% if params[:action] == 'new'  %>
  <small id="isbnHelp" class="form-text text-muted">Quickly add metadata from Google Books</small>
    <div class="form-group">
      <label for="edition_isbn13">ISBN13</label>    
      <%= text_field(:edition, :isbn13, class: 'form-control', placeholder: '9780307739452') %>
    </div>

    <span class="ml-2 mr-2">OR</span>

    <div class="form-group">
      <label for="edition_isbn10">ISBN10</label>
      <%= text_field(:edition, :isbn10, class: 'form-control', placeholder: '0307739457')  %>
    </div>

    <button class="btn btn-primary ml-2" id="lookupISBN" type="submit">Search <i class="fa fa-search fa-lg" alt="success"></i></button><div id="lookup-status-container"><button class="btn" id="lookup-status"></button><span id="lookup-failure-message">Hmm...no results. Try again?</span></div>

  <% else %>
    <div class="form-group">
      <label for="edition_isbn13">ISBN13</label>    
      <%= text_field(:edition, :isbn13, class: 'form-control', placeholder: '9780307739452', disabled: 'true') %>
    </div>

    <span class="ml-2 mr-2">OR</span>

    <div class="form-group">
      <label for="edition_isbn10">ISBN10</label>
      <%= text_field(:edition, :isbn10, class: 'form-control', placeholder: '0307739457', disabled: 'true')  %>
    </div>
  <% end %>

</div>

app/views/editions/_new.html.erb
<div class="form-group">
  <label for="editionPublicationyear">Publication Year</label>
  <input type="text" name="edition[publication_year]" id="editionPublicationyear" class="form-control">
</div>

app/views/editions/index.html.erb
<h2>All Editions</h2>
<table class="table table-striped table-responsive">
  <thead>
    <th>Author</th>
    <th>Title</th>
    <th>Publisher</th>
    <th>Publication Year</th>
    <th>ISBN13</th>
  </thead>
<% @editions.each do |edition| %>
  <tr>
    <td><%= edition.authors[0].name %></td>
    <td><%= edition.work.title %></td>
    <td><%= edition.publisher.name %></td>
    <td><%= edition.publication_year %></td>
    <td><%= edition.isbn13 %></td>
  </tr>
<% end %>
</table
<p>
  <%= link_to 'New Edition', new_edition_path %>
</p>

app/views/editions/new.html.erb
<h2>Edition</h2>

<form id="new-edition-form" method="POST" action="/editions">
  <%= render "authors/new"%>
  <%= render "works/new"%>
  <%= render "publishers/new"%>
  <%= render "editions/new"%>
  <button class="btn" type="submit">Submit</button>
</form>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<h2>Edition</h2>
<p><%= @edition.authors[0].name %></p>
<p><%= @edition.work.title %></p>
<p><%= @edition.publisher.name %></p>
<p><%= @edition.publication_year %></p>
<p><%= @edition.isbn13 %></p>