config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations:'users/registrations', sessions: 'users/sessions' }
  
  authenticate :user do
    resources :users do
      resources :copies
      resources :friendships
    end
    resources :copies do
      resources :loans
    end
    resources :authors
    resources :works
    resources :publishers
    resources :editions
    resources :friendrequests
    resources :loans
  end
  
  root "demo#welcome"
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :owner, foreign_key: "user_id",class_name: "User"
  belongs_to :edition
  belongs_to :format

  validates :edition, presence: true
  validates :owner, presence: true
  validate :url_valid?, if: 'url.present?'


  def url_valid?
    copy_url = URI(url) rescue false
    errors.add(:url, "not a valid URL") unless (copy_url.kind_of?(URI::HTTP) || copy_url.kind_of?(URI::HTTPS))
  end 

  def available?
    Loan.where(copy_id: id, status_code: 1).empty?
  end

  def requested?(current_user)
    Loan.where(borrower: current_user, copy_id: id, status_code: 0).exists?
  end

  def loan_pending?
    Loan.where(copy_id: id, status_code: 0).exists?
  end

  def borrowed?
    Loan.where(copy_id: id, status_code: 1).exists?
  end
  
  def current_loan
    Loan.find_by(copy_id: id, status_code: 1)
  end

  def self.csv_export
    attributes = %w{id user_id acquisition_date url edition_id format_id}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |copy|
        csv << attributes.map { |attr| copy.send(attr)}
      end
    end
  end

  def full_record
    copy_info = {acquisition_date: acquisition_date, url: url}
    edition = Edition.find(self.edition_id)
    publisher = Publisher.find(edition.publisher_id)
    work = Work.find(edition.work_id)
    author = Author.find(work.author_id)
    format = Format.find(format_id)

    copy_info[:publication_year] = edition.publication_year
    copy_info[:isbn10] = edition.isbn10
    copy_info[:isbn13] = edition.isbn13
    copy_info[:publisher] = publisher.name
    copy_info[:work] = work.title
    copy_info[:author] = author.name

    copy_info
  end

end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_copy, only: [:show, :edit, :update, :destroy]
  before_action :set_metadata, only: [:show, :edit, :update]

  def index
    @user = User.find(params[:user_id])
    # Only allow users to view their own library or their friends' libraries
    if access_authorized?(@user) == false
      redirect_to root_url
    end
    @copies = Copy.where(user_id: params[:user_id])
    respond_to do |format|
      format.html
      format.csv { send_data @copies.csv_export, filename: "library.csv"}
    end
  end

  def new
    @copy = Copy.new
    @formats = Format.all
    if current_user != User.find(params[:user_id])
      redirect_to root_url
    end
  end

  def edit
    @formats = Format.all
  end

  def create
    @author = Author.find_or_create_by(author_params)
    @work = Work.find_or_create_by(work_params.merge(author_id: @author.id))
    @publisher = Publisher.find_or_create_by(publisher_params)
    @edition = Edition.find_or_create_by(edition_params.merge(work_id: @work.id, publisher_id: @publisher_id))
    @copy = Copy.find_or_initialize_by(copy_params.merge(edition_id: @edition.id,user_id: current_user.id))
    
    if @copy.save
      redirect_to user_copy_path(current_user,@copy)
    else
      render :new
    end
  end

  def update
    if @copy.update(copy_params)
      redirect_to user_copy_path(@copy.owner, @copy)
    else
      render :edit
    end
  end

  def show
    @format = @copy.format
    if access_authorized?(@copy.owner) == false
      redirect_to root_url
    end
  end

  def destroy
    @copy.destroy
    redirect_to copies_path
  end

  private

  # params
  def copy_params
    params.require(:copy).permit(:user_id, :edition_id, :acquisition_date, :format_id, :url)
  end

  def edition_params
    params.require(:edition).permit(:author_id, :work_id, :publisher_id, :publication_year, :isbn10, :isbn13)
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def work_params
    params.require(:work).permit(:title)
  end

  def author_params
    params.require(:author).permit(:name)
  end

  # filters

  def set_copy
    @copy = Copy.find(params[:id])
  end

  def set_metadata
    @edition = @copy.edition
    @work = @edition.work
    @publisher = @edition.publisher
    @work = @edition.work
    @author = @work.author
  end

end

app/views/copies/_form.html.erb
<%= form_for(copy) do |f| %>  
  
  <%= render "editions/isbns"%>

  <% if params[:action] == 'edit' %>
    <div class="form-group">
      <%= label_tag(:author) %>
      <%= text_field(:author, :name, class: 'form-control', disabled: 'true')  %>
    </div>  

    <div class="form-group">
      <%= label_tag(:work, 'Title') %>
      <%= text_field(:work, :title, class: 'form-control', disabled: 'true')  %>
    </div>  

    <div class="form-group">
      <%= label_tag(:publisher, 'Publisher') %>
      <%= text_field(:publisher, :name, class: 'form-control', disabled: 'true') %>  
    </div>

    <div class="form-group">
      <%= label_tag(:edition, 'Publication Year') %>
      <%= text_field(:edition, :publication_year, class: 'form-control', disabled: 'true')  %>  
    </div>
  <% else %>
    <div class="form-group">
      <%= label_tag(:author) %>
      <%= text_field(:author, :name, class: 'form-control')  %>
    </div>  

    <div class="form-group">
      <%= label_tag(:work, 'Title') %>
      <%= text_field(:work, :title, class: 'form-control')  %>
    </div>  

    <div class="form-group">
      <%= label_tag(:publisher, 'Publisher') %>
      <%= text_field(:publisher, :name, class: 'form-control') %>  
    </div>

    <div class="form-group">
      <%= label_tag(:edition, 'Publication Year') %>
      <%= text_field(:edition, :publication_year, class: 'form-control')  %>  
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url, 'Download URL'%>
    <%= f.text_field :url, class: 'form-control', placeholder: 'http://' %>
  </div>

  <div class="form-group">
    <%= f.label :format_id, "Format" %>
    <%= f.collection_select(:format_id, Format.all, :id, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :acquistion_date %>
    <%= date_field :copy, :acquisition_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/copies/edit.html.erb
<h1>Editing <em><%= @copy.edition.work.title %></em></h1>

<%= render 'form', copy: @copy %>

app/views/copies/index.html.erb
<h2><%= @user.name%>'s Books</h2>
<table class="table table-hover table-striped table-responsive">
  <thead>
    <th>Author</th>
    <th>Title</th>
    <th>Publisher</th>
    <th>Publication Year</th>
    <th>ISBN13</th>
    <th>Format</th>
    <th>Edit</th>
    <th>Status</th>
  </thead>
<% @copies.each do |copy| %>
  <tr>
    <td><%= copy.edition.authors[0].name %></td>
    <td><%= copy.edition.work.title %></td>
    <td><%= copy.edition.publisher.name %></td>
    <td><%= copy.edition.publication_year %></td>
    <td><%= copy.edition.isbn13 %></td>
    <td><%= copy.format.name %></td>
    <td><%= link_to '<i class="fa fa-search" aria-hidden="true"></i>'.html_safe, user_copy_path(@user,copy), alt: "View record: #{copy.edition.work.title}" %></td>  
    <td class="action-column">
      <!-- download -->
      <% if !copy.url.empty? %>
        <%= link_to 'Download', copy.url, class: "btn btn-success", target: "_blank" %>
      <% elsif copy.requested?(current_user) %>
        <button class="btn btn-warning btn-requested">Requested</button>
      <% elsif copy.loan_pending? %>
        <%= link_to 'Review Request', loans_path, method: :get, class: "btn btn-warning" %>
      <% elsif copy.borrowed? %>
        Borrowed
      <% elsif @user != current_user && copy.available?%>
        <%= link_to 'Borrow', copy_loans_path(copy), method: :post, class: "btn btn-primary btn-borrow" %>
      <% else %>
        -
      <% end %>
    </td>
  </tr>
<% end %>
</table>
<p>
  <% if @user == current_user %>
    <%= link_to 'Add books', new_user_copy_path(current_user) %>
  <% end %>
</p>

app/views/copies/new.html.erb
<h2>Add a Book</h2>

<% if @copy.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@copy.errors.count, "error") %> prohibited this copy from being saved:</h2>
 
    <ul>
    <% @copy.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', copy: @copy %>

app/views/copies/show.html.erb
<h2><%= @author.name %>, <em><%= @work.title %></em></h2>
<p>Owner: <%= link_to @copy.owner.name, user_copies_path(@copy.owner) %></p>
<p><%= @publisher.name %>, <%= @edition.publication_year %></p>
<p>ISBN13: <%= @edition.isbn13 %> <% if !@edition.isbn10.empty? %>| ISBN10: <%= @edition.isbn10 %><% end %></p>
<p><%= @copy.format.name %></p>
<p>Acquired: <%= @copy.acquisition_date.strftime('%B %d, %Y') unless @copy.acquisition_date == nil %>

<p><% if !@copy.url.empty? %>
  <%= link_to 'Download', @copy.url, class: "btn btn-success", target: "_blank" %>
  <% elsif @copy.requested?(current_user) %>
    <button class="btn btn-warning btn-requested">Requested</button>
  <% elsif @copy.loan_pending? %>
    <%= link_to 'Review Request', loans_path, method: :get, class: "btn btn-warning" %>
  <% elsif @copy.borrowed? %>
    Status: Currently borrowed by <%= link_to @copy.current_loan.borrower.name, user_copies_path(@copy.current_loan.borrower) %>
    <%=  %>
  <% elsif @copy.owner != current_user && @copy.available?%>
    <%= link_to 'Borrow', copy_loans_path(@copy), method: :post, class: "btn btn-primary btn-borrow" %>
<% end %></p>

<%= link_to 'Back', user_copies_path(@copy.owner), class: "btn btn-primary" %>

<%= link_to 'Edit', edit_user_copy_path(@copy), class: "btn btn-warning" %>

<%= link_to 'Delete', user_copy_path(@copy), class: "btn btn-danger", method: :delete %>