config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations:'users/registrations', sessions: 'users/sessions' }
  
  authenticate :user do
    resources :users do
      resources :copies
      resources :friendships
    end
    resources :copies do
      resources :loans
    end
    resources :authors
    resources :works
    resources :publishers
    resources :editions
    resources :friendrequests
    resources :loans
  end
  
  root "demo#welcome"
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :works
  has_many :editions, through: :works
  accepts_nested_attributes_for :works
  validates :name,
    presence: true,
    uniqueness: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])

    @author.destroy
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
end

app/views/authors/_new.html.erb
<div class="form-group">
<label for="authorName">Author</label>
<input type="text" name="author[name]" id="authorName" class="form-control" >
</div>

app/views/authors/index.html.erb
<h2>All Authors</h2>
<ul>
<% @authors.each do |author| %>
  <li><%= link_to author.name, author_path(author) %></li>
<% end %>
</ul>
<p>
  <%= link_to 'New Author', new_author_path %>
</p>

app/views/authors/new.html.erb
<h2>Author</h2>
<%= simple_form_for @author do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h2>Author: <%= @author.name %></h2>

<h3>Works</h3>
<ul>
<% @author.works.each do |work| %>
  <li><%= link_to work.title, work_path(work) %></li>
<% end %>

<%= link_to 'Back', authors_path %>