config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations:'users/registrations', sessions: 'users/sessions' }
  
  authenticate :user do
    resources :users do
      resources :copies
      resources :friendships
    end
    resources :copies do
      resources :loans
    end
    resources :authors
    resources :works
    resources :publishers
    resources :editions
    resources :friendrequests
    resources :loans
  end
  
  root "demo#welcome"
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def welcome
    render 'welcome'
  end
end

app/views/demo/welcome.html.erb
<div class="text-xs-center" >
  <%= image_tag "prium.png"%>

  <% if user_signed_in? %>
  <p class="lead">Hi, <%= current_user.name %>! Here are some things you can do:</p>
  <ul>
    <div class="col-sm-6"><div class="card card-block"><%= link_to 'Add a book', new_user_copy_path(current_user), class: "card-title" %><p class="card-text">Grow your collection</p></div></div>
    <div class="col-sm-6"><div class="card card-block"><%= link_to 'Your library', user_copies_path(current_user), class: "card-title" %><p class="card-text">Manage your collection</p></div></div>
    <div class="col-sm-6"><div class="card card-block"><%= link_to 'Friends', user_friendships_path(current_user), class: "card-title" %><p class="card-text">Explore your friends' libraries</p></div></div>
    <div class="col-sm-6"><div class="card card-block"><%= link_to 'Add friends', friendrequests_path, class: "card-title" %><p class="card-text">Invite friends to Sheaf</p></div></div>
    <div class="col-sm-6"><div class="card card-block">
    <% if current_user.pending_requests.length > 0 %>
    <%= link_to "Loans <span class='notification-counter'>#{current_user.pending_requests.length}</span>".html_safe, loans_path, class: "card-title" %>
    <% else %>
      <%= link_to 'Loans', loans_path, class: "card-title" %>
    <% end %>
    <p class="card-text">Books you're borrowing and lending</p></div></div>
  </ul>

  <% else %>

  <p class="lead">an app for friends and books</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary btn-lg"%>
  <%= link_to 'Log In', new_user_session_path, class: "btn btn-secondary btn-lg"%>

  <% end %>
</div>